name: Push Docker image to EC2

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t docker-react .

    - name: Save Docker image as tar file
      run: docker save docker-react:latest | gzip > docker-react.tar.gz
      
    - name: Copy Docker image to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker-react.tar.gz"
        target: "/tmp/"

    - name: Load Docker image on EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cat /tmp/docker-react.tar.gz | docker load
